services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/devjourney
      - public-data:/devjourney/public
      - tmp-data:/devjourney/tmp
      - log-data:/devjourney/log
    networks:
      - devjourney-network
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devjourney_development
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - devjourney-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/devjourney/public
      - tmp-data:/devjourney/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - devjourney-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  devjourney-network:
    external: true
