default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "devjourney_development" } %>

test:
  <<: *default
  database: devjourney_development

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

